# Generated by Django 4.1.8 on 2023-04-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalId', models.IntegerField(max_length=200, unique=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('barcode', models.IntegerField(blank=True, null=True)),
                ('retailPrice', models.PositiveIntegerField(blank=True, null=True)),
                ('wholesalePrice', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
